### PR TITLE
Added polish translation

### PR DESCRIPTION
**Pull request by wojciechgizynski**

### CODE REVIEW

**Comment by evanbrumley** [comment]
Thankyou! The translation is now live :-)

**Comment by wojciechgizynski** [comment]
Thank you for making the app! It's much better than playing with cards and it's language independent.

I've checked the polish translation on the live version and I can see that the polish letters are not supported by the font you're using. Here's an image: http://i.imgur.com/FjlkJct.png

Problematic letters are ęąóśłżźćńĘĄÓŚŁŻŹĆŃ. I've checked the Raleway font on the Google Fonts (http://www.google.com/fonts#UsePlace:use/Collection:Raleway) and there is no Latin Extended subset available for it. Can something be done about this or would you have to change a font to make it look good all the way? :)

**Comment by evanbrumley** [comment]
Ah, thanks for letting me know. I've added a little bit of css that should swap the font over to Open Sans when Polish is selected.

**Comment by wojciechgizynski** [comment]
Works great, thank you!

2015-02-10 12:48 GMT+01:00 evanbrumley <notifications@github.com>:

> Ah, thanks for letting me know. I've added a little bit of css that should
> swap the font over to Open Sans when Polish is selected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evanbrumley/spyfall/pull/1#issuecomment-73687008>.
>



-- 
gizynski at gmail.com

**Pull request merged**
