### PR TITLE
Created translation for croatian

### PR DESCRIPTION
**Pull request by DamirCiganovic-Jankovic**

### CODE REVIEW

**Comment by DamirCiganovic-Jankovic** [comment]
Our word for croatian language is "Hrvatski"

**Comment by evanbrumley** [comment]
Thanks Damir! I've integrated your translation and will deploy in a few hours once the Americans go to bed and site traffic dies down a little :-)

**Comment by evanbrumley** [comment]
Deployed. Thanks for the contribution!

**Comment by DamirCiganovic-Jankovic** [comment]
cool :)

**Pull request merged**
