### PR TITLE
Moved game set-up code to server and various bugfixes

### PR DESCRIPTION
**Pull request by gavinksong**
I moved the game set-up code (including location and role assignment) to the server side and also implemented the following:

- Display a spinner while game is being set up.
- Players are now removed from a game when they leave the page (without pressing the "Leave Game" button).
- Players are returned to the lobby if the spy leaves the game.
- Players who join a game while it is in progress are assigned the "default role" (instead of null).
- The "Create" and "Join" buttons don't do anything if "isLoading" is true. This prevents people from spamming the buttons and breaking something.

This is my first contribution on Github. Also my first time with Meteor and web development in general. Please go over my code. I've tested it, and everything seems to be working for me. I think all the changes I've made are positive, and I hope you approve of them. :)

### CODE REVIEW

**Comment by evanbrumley** [comment]
Nice! Thanks for the contribution, and welcome to Github! I'll take a look through your improvements over the next couple of days and let you know how it goes :-)

**Comment by gavinksong** [comment]
I just added another commit where I added the memory aids suggested in Issue #28. I also removed the href attribute from the countdown timer, because it sometimes kicks me out of a game when I click it. I added 'cursor: pointer' to the stylesheet instead, so that users know that the countdown timer is still clickable (for pausing the game).

**Comment by evanbrumley** [comment]
Merged and deployed - thanks again for the contribution! The only slight change I had to make was to take out the code that stopped games if the spy dropped out, as it was triggering during game setup if a player had been a spy in a previous game.

**Comment by gavinksong** [comment]
Thanks! I'm really glad that you found most of my code acceptable. I'm sorry about the bug. It's actually amazing that you caught it so fast. If you're interested, I made a fix to the code in my repository to check the game state before stopping the game. It should work.

**Pull request merged**
